/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jeyson Diez
 */
public class reporte_consulta extends javax.swing.JFrame {

    /**
     * Creates new form reporte_consulta
     */
    public reporte_consulta() {
        initComponents();
        setLocationRelativeTo(null);
        Principal inii = new Principal();
            Connection conect=null;
            conectar cc = new conectar();
            Principal in = new Principal();
            conect=cc.conexion();
            float bal=0;
            String Nom="";
        try {
            
            //String sql2="SELECT balance from clientes WHERE cod_cli='"+in.pru.getText();
      
            String sql2="SELECT balance,nom_cli from clientes WHERE cod_cli='"+inii.pru.getText()+"'";
            
            Statement st2 = conect.createStatement();
            ResultSet rs2 = st2.executeQuery(sql2);
            
            while (rs2.next()) {
                bal = rs2.getFloat(1);
                Nom = rs2.getString(2); // index 1 is the "id" column
                // index 2 is the "name" column
                System.out.println(bal);
                System.out.println(Nom);
                
            }
            
            lbalance.setText("RD$ "+String.valueOf(bal));
            lnombre.setText(Nom);
        } catch (SQLException ex) {
            Logger.getLogger(Consulta_Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbalance = new javax.swing.JLabel();
        lbalance1 = new javax.swing.JLabel();
        lbalance2 = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lnombre1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnombre2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lnombre3 = new javax.swing.JLabel();
        lbalance3 = new javax.swing.JLabel();
        lbalance4 = new javax.swing.JLabel();
        lbalance5 = new javax.swing.JLabel();
        lbalance6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lnombre4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lnombre5 = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Correo:");

        lbalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance.setForeground(new java.awt.Color(255, 0, 0));
        lbalance.setText("0");

        lbalance1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance1.setText("Saldo Actual:");

        lbalance2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance2.setText("Nombre de Usuario:");

        lnombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre.setForeground(new java.awt.Color(255, 0, 0));
        lnombre.setText("Juan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Hora");

        lnombre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre1.setForeground(new java.awt.Color(255, 0, 0));
        lnombre1.setText("4:30 PM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fecha");

        lnombre2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre2.setForeground(new java.awt.Color(255, 0, 0));
        lnombre2.setText("11/08/17");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cajero");

        lnombre3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre3.setForeground(new java.awt.Color(255, 0, 0));
        lnombre3.setText("BCD001");

        lbalance3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance3.setText("Comision:");

        lbalance4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance4.setForeground(new java.awt.Color(255, 0, 0));
        lbalance4.setText("RD$ 0.00");

        lbalance5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance5.setText("IVA Comision:");

        lbalance6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbalance6.setForeground(new java.awt.Color(255, 0, 0));
        lbalance6.setText("RD$ 0.00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Banco central Dominicano, SA");

        lnombre4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre4.setForeground(new java.awt.Color(255, 0, 0));
        lnombre4.setText("bcdefectivo@hotmail.com");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Telefono:");

        lnombre5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lnombre5.setForeground(new java.awt.Color(255, 0, 0));
        lnombre5.setText("+1-809-275-0203");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnombre5)
                                    .addComponent(lnombre4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbalance1)
                                    .addComponent(lbalance3)
                                    .addComponent(lbalance5)
                                    .addComponent(lbalance2))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnombre)
                                    .addComponent(lbalance4)
                                    .addComponent(lbalance)
                                    .addComponent(lbalance6)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(183, 183, 183)
                                .addComponent(jLabel2)
                                .addGap(210, 210, 210))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lnombre2)
                                .addGap(150, 150, 150)
                                .addComponent(lnombre1)
                                .addGap(195, 195, 195)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lnombre3)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnombre3)
                    .addComponent(lnombre2)
                    .addComponent(lnombre1))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbalance2)
                    .addComponent(lnombre))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbalance1)
                    .addComponent(lbalance))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbalance3)
                    .addComponent(lbalance4))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbalance5)
                    .addComponent(lbalance6))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lnombre4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lnombre5))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte_consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbalance;
    private javax.swing.JLabel lbalance1;
    private javax.swing.JLabel lbalance2;
    private javax.swing.JLabel lbalance3;
    private javax.swing.JLabel lbalance4;
    private javax.swing.JLabel lbalance5;
    private javax.swing.JLabel lbalance6;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lnombre1;
    private javax.swing.JLabel lnombre2;
    private javax.swing.JLabel lnombre3;
    private javax.swing.JLabel lnombre4;
    private javax.swing.JLabel lnombre5;
    // End of variables declaration//GEN-END:variables
}
